### ISSUE TITLE
Level 50 redstone door 

### ISSUE THREAD

**Issue by TheoP69** [Wholy/CrafterWars-Parkour#2]
The redstone door in level 50 (the room with the long red carpet).

**Comment by Wholy** [comment]
Ok, thank you for report me this ;) I will fix it in my next log.

**Comment by Wholy** [comment]
The door is working now 

![image](https://user-images.githubusercontent.com/29717533/121256037-0d675680-c8a4-11eb-88bb-0ec993c1a95c.png)
