### ISSUE TITLE
Cobwebs glitching players, in BOTH parkour worlds!

### ISSUE THREAD

**Issue by TheoP69** [Wholy/CrafterWars-Parkour#3]
When you fall into a cobweb, it glitches the player. This also prevents you from completing certain jumps, such as 4 blockers with cobwebs, etc. As it will always glitch you in them.
This occurs on the new parkour map, and the old one. So, it must be one of the plugins causing this (possibly), perhaps “essentials anti-build” has an interference with this.
This glitch only happens on your server when in gamemode survival, and you do not get glitched when in gamemode creative.

**Comment by Wholy** [comment]
Can you explain me how is the glitch with the cowebs please? If you can provide a video, let me know.

**Comment by Wholy** [comment]
The cowebs is real this is from minecraft, I will remove some of them
