### ISSUE TITLE
Acceso a Lobby

### ISSUE THREAD

**Issue by byggames** [Wholy/CrafterWars-Parkour#7]
Hola, te escribo porque cada vez que voy al parkour estoy encerrado en jn parkour wue no soy capaz de pasar, podrías hacer un boton de reiniciar tu personaje en el parkour o algo asi

**Comment by Wholy** [comment]
Hola crack, a que te refieres, podrias mandarme una foto para verlo/entenderlo please? 
Saludos

**Comment by byggames** [comment]
Si, ahora cuando entre te mando una cap. La surgerencia seria wue en cualquier momento puedas volver a la selección de parkours y no quedarte atrapado. Saludos

**Comment by byggames** [comment]
De por si este Issue se puede cerrar porque ya me sacastes. Un saludo y gracias crack
